FROM balenalib/raspberrypi3-python:3.7-buster

RUN echo "$(cat /dev/urandom | tr -dc _A-Z-a-z-0-9 | head -c${1:-10})" > /CONTAINER_ID

RUN apt-get update \
    && apt-get -y install --no-install-recommends \
    build-essential \
    git \
    libusb-dev \
    mpg321 \
    && rm -rf /var/lib/apt/lists/*

# Install latest PIP
RUN curl https://bootstrap.pypa.io/get-pip.py --output get-pip.py \
    && python3 get-pip.py \
    && rm -f get-pip.py

# Install Pillow dependencies
# See: https://pillow.readthedocs.io/en/latest/installation.html#external-libraries
RUN apt-get update \
    && apt-get -y install --no-install-recommends \
    zlib1g-dev \
    libjpeg-dev \
    libtiff5 \
    libfreetype6-dev \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /app
WORKDIR /app

# Install any needed packages specified in requirements.txt
ADD requirements.txt /app/requirements.txt
RUN pip3 install --trusted-host pypi.python.org -r requirements.txt

# Install CCTALK module fork
RUN git clone https://github.com/gorodulin/pycctalk.git /tmp/_pycctalk \
    && pip3 install /tmp/_pycctalk \
    && rm -rf /tmp/_pycctalk

RUN mkdir /data
COPY . /app

ENV LOGLEVEL=INFO

VOLUME ["/data"]
VOLUME ["/sys/fs/cgroup"]
